accounts:
  - account: bob
    coins: ["10000token", "100000000stake"]
validator:
  account: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
build:
  main: cmd/digd
