# Tests the state sync script

name: State Sync

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    name: State Sync
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with: 
          go-version: '^1.17'
      - name: state sync
        run: |
           git clone https://github.com/facebook/rocksdb
           cd rocksdb
           sudo make install
           cd ../dig
           bash statesyncrock.bash
           
